theme: jekyll-theme-cayman

title: Sergei Turukin
description: Deep Learning software engineer
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Sergei Turukin
  url:

links:
  linkedin: sergei-turukin-036ba965/?locale=en_US
  github: rampage644
  email: rampage644@gmail.com

# Gems
gems:
  - jekyll-paginate

google_analytics: UA-93025085-1

#Others
markdown: kramdown
